from django.contrib import admin
from globallometree.apps.locations.models import Continent, Country, Location, LocationGroup
from globallometree.apps.locations.models import BiomeFAO, BiomeUdvardy, BiomeWWF, DivisionBailey, BiomeHoldridge

class ContinentAdmin(admin.ModelAdmin):
    list_display = ('Name', 'Code')


class CountryAdmin(admin.ModelAdmin):
    list_display = ('Common_name', 'Common_name_fr', 'Iso3166a2', 'Continent', 'Centroid_longitude', 'Centroid_latitude')
    list_filter  = ('Continent', )


class LocationAdmin(admin.ModelAdmin):
    list_display = ('Name', 'Biome_fao', 'Country', 'Modified')
    list_filter  = ('Biome_fao','Country')


class LocationInline(admin.TabularInline):
    #Bit of a hack to use the autogenerated through model, but it avoides the horrible multiselect
    model = LocationGroup.Locations.through
    raw_id_fields = ('location',)

class LocationGroupAdmin(admin.ModelAdmin):
    list_display = ('Name', 'Original_group_location', 'Modified')
    search_fields = ('Name', 'Original_group_location')
    exclude = ('Locations',)
    inlines = [
    	 LocationInline,
    	]

class BiomeFAOAdmin(admin.ModelAdmin):
    list_display = ('Name', )


class BiomeUdvardyAdmin(admin.ModelAdmin):
    list_display = ('Name', )


class BiomeWWFAdmin(admin.ModelAdmin):
    list_display = ('Name', )


class DivisionBaileyAdmin(admin.ModelAdmin):
    list_display = ('Name', )


class BiomeHoldridgeAdmin(admin.ModelAdmin):
    list_display = ('Name', )    


admin.site.register(Continent, ContinentAdmin)
admin.site.register(Country, CountryAdmin)
admin.site.register(Location, LocationAdmin)
admin.site.register(LocationGroup, LocationGroupAdmin)
admin.site.register(BiomeFAO, BiomeFAOAdmin)
admin.site.register(BiomeUdvardy, BiomeUdvardyAdmin)
admin.site.register(BiomeWWF, BiomeWWFAdmin)
admin.site.register(DivisionBailey, DivisionBaileyAdmin)
admin.site.register(BiomeHoldridge, BiomeHoldridgeAdmin)
