from django.contrib import admin
from globallometree.apps.locations.models import Continent, Country, Location, LocationGroup
from globallometree.apps.locations.models import BiomeFAO, BiomeUdvardy, BiomeWWF, DivisionBailey, BiomeHoldridge

class ContinentAdmin(admin.ModelAdmin):
    list_display = ('name', )


class CountryAdmin(admin.ModelAdmin):
    list_display = ('common_name', 'capital', 'continent')
    list_filter  = ('continent', )


class LocationAdmin(admin.ModelAdmin):
    list_display = ('name', 'biome_fao', 'country', 'modified')
    list_filter  = ('biome_fao','country')


class LocationInline(admin.TabularInline):
    #Bit of a hack to use the autogenerated through model, but it avoides the horrible multiselect
    model = LocationGroup.locations.through
    raw_id_fields = ('location',)

class LocationGroupAdmin(admin.ModelAdmin):
    list_display = ('group_name', 'original_Group_Location', 'modified')
    search_fields = ('group_name', 'original_Group_Location')
    exclude = ('locations',)
    inlines = [
    	 LocationInline,
    	]

class BiomeFAOAdmin(admin.ModelAdmin):
    list_display = ('name', )


class BiomeUdvardyAdmin(admin.ModelAdmin):
    list_display = ('name', )


class BiomeWWFAdmin(admin.ModelAdmin):
    list_display = ('name', )


class DivisionBaileyAdmin(admin.ModelAdmin):
    list_display = ('name', )


class BiomeHoldridgeAdmin(admin.ModelAdmin):
    list_display = ('name', )    


admin.site.register(Continent, ContinentAdmin)
admin.site.register(Country, CountryAdmin)
admin.site.register(Location, LocationAdmin)
admin.site.register(LocationGroup, LocationGroupAdmin)
admin.site.register(BiomeFAO, BiomeFAOAdmin)
admin.site.register(BiomeUdvardy, BiomeUdvardyAdmin)
admin.site.register(BiomeWWF, BiomeWWFAdmin)
admin.site.register(DivisionBailey, DivisionBaileyAdmin)
admin.site.register(BiomeHoldridge, BiomeHoldridgeAdmin)
