from django.contrib import admin
from globallometree.apps.taxonomy.models import (
    Family, 
    Genus, 
    Species, 
    SpeciesGroup,
    SpeciesLocalName, 
    Subspecies,
    SubspeciesLocalName
    )


class FamilyAdmin(admin.ModelAdmin):
    list_display = ('Name', 'Modified')
    search_fields  = ('Name',)


class GenusAdmin(admin.ModelAdmin):
    list_display = ('Name', 'Family',  'Modified')
    search_fields  = ('Name','Family__Name', )
    read_only_fields = ('Created', 'Modified')


class SpeciesLocalNameInline(admin.TabularInline):
    model = SpeciesLocalName


# class SpeciesLocalNameAdmin(admin.ModelAdmin):
#     raw_id_fields = ('Species',)
#     list_display = ('Local_name_latin', 'Species', 'Local_name', 'Language_iso_639_3')
#     search_fields  = ('Local_name', 'Local_name_latin', 'Language_iso_639_3')    


class SubspeciesLocalNameInline(admin.TabularInline):
    model = SubspeciesLocalName


class SubspeciesAdmin(admin.ModelAdmin):
    raw_id_fields = ('Species',)
    list_display = ('Name', 'Species', 'Modified')
    search_fields  = ('Name','Species__Genus__Family__Name', 'Species__Genus__Name', 'Species__Name' )
    read_only_fields = ('created', 'modified')
    inlines = (SubspeciesLocalNameInline,)


# class SubspeciesLocalNameAdmin(admin.ModelAdmin):
#     raw_id_fields = ('subspecies',)
#     list_display = ('local_name_latin', 'subspecies', 'local_name', 'language_iso_639_3')
#     search_fields = ('local_name', 'local_name_latin', 'language_iso_639_3') 


class SpeciesAdmin(admin.ModelAdmin):
    raw_id_fields = ('Genus',)
    list_display = ('Name', 'Genus', 'Modified')
    search_fields  = ('Name','Genus__Family__Name', 'Genus__Name', )
    read_only_fields = ('Created', 'Modified')
    inlines = (SpeciesLocalNameInline,)


class SpeciesInline(admin.TabularInline):
    #Bit of a hack to use the autogenerated through model, but it avoides the horrible multiselect
    model = SpeciesGroup.Species.through
    raw_id_fields = ('species',)


class SpeciesGroupAdmin(admin.ModelAdmin):
    list_display = ('Name', 'Original_ID_Group', 'Modified')
    search_fields  = ('Name','Original_ID_Group', )
    read_only_fields = ('Created', 'Modified')
    inlines = [
        SpeciesInline,
    ]
    exclude = ('Species',)


admin.site.register(Family, FamilyAdmin)
admin.site.register(Genus, GenusAdmin)
admin.site.register(Species, SpeciesAdmin)
admin.site.register(Subspecies, SubspeciesAdmin)
admin.site.register(SpeciesGroup, SpeciesGroupAdmin)
